'use client';
import { useEffect, useState } from 'react';
import { RefreshCw, Download, Save } from 'lucide-react';
type Prices={a4_bw:number;a4_colour:number;a3_bw:number;a3_colour:number;single_side:number;double_side:number;spiral_binding:number};
type Order={id:string;order_number:string;customer_name:string;phone:string;email:string;file_name:string;pages:number;copies:number;print_type:string;paper_size:string;print_side:string;binding:string;estimated_price:number;final_price:number|null;status:string;admin_notes:string;created_at:string};
const keys: (keyof Prices)[]=['a4_bw','a4_colour','a3_bw','a3_colour','single_side','double_side','spiral_binding'];
const labels:Record<keyof Prices,string>={a4_bw:'A4 B&W / page',a4_colour:'A4 Colour / page',a3_bw:'A3 B&W / page',a3_colour:'A3 Colour / page',single_side:'Single side surcharge',double_side:'Double side surcharge',spiral_binding:'Spiral binding'};
export default function AdminXeroxPage(){
 const [orders,setOrders]=useState<Order[]>([]);const [prices,setPrices]=useState<Prices|null>(null);const [busy,setBusy]=useState(true);const [notice,setNotice]=useState('');
 async function load(){setBusy(true);try{const r=await fetch('/api/admin/xerox');const d=await r.json();if(!r.ok)throw Error(d.error);setOrders(d.orders);setPrices(d.pricing);}catch(e){setNotice(e instanceof Error?e.message:'Could not load data.')}finally{setBusy(false)}}
 useEffect(()=>{load()},[]);
 async function save(body:unknown){setNotice('');const r=await fetch('/api/admin/xerox',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok){setNotice(d.error);return false}setNotice('Saved.');return true}
 async function download(id:string){const r=await fetch('/api/admin/xerox',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});const d=await r.json();if(!r.ok){setNotice(d.error);return}window.open(d.url,'_blank','noopener,noreferrer')}
 const input='rounded-lg border border-charcoal-700 bg-charcoal-900 px-3 py-2 text-sm text-white';
 return <div className="space-y-8"><div><p className="text-xs uppercase tracking-widest text-gold-400">Service management</p><h1 className="mt-2 text-3xl font-bold text-white">Xerox &amp; Printing</h1><p className="mt-2 text-sm text-charcoal-300">Review print requests, securely download documents and set current prices.</p></div>
 {notice&&<p role="status" className="rounded-xl border border-charcoal-700 bg-charcoal-950 p-3 text-sm text-gold-300">{notice}</p>}
 {prices&&<section className="rounded-2xl border border-charcoal-800 bg-charcoal-950 p-5"><h2 className="mb-4 text-lg font-bold text-white">Current pricing (₹)</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{keys.map(k=><label key={k} className="text-xs text-charcoal-300">{labels[k]}<input type="number" min="0" step="0.01" className={`${input} mt-1 block w-full`} value={prices[k]} onChange={e=>setPrices({...prices,[k]:Number(e.target.value)})}/></label>)}</div><button onClick={()=>save({pricing:prices})} className="mt-4 inline-flex items-center gap-2 rounded-lg bg-gold-400 px-4 py-2 text-sm font-bold text-burgundy-950"><Save className="h-4 w-4"/>Save prices</button></section>}
 <section className="overflow-hidden rounded-2xl border border-charcoal-800 bg-charcoal-950"><div className="flex items-center justify-between border-b border-charcoal-800 p-5"><h2 className="text-lg font-bold text-white">Print requests</h2><button onClick={load} className="inline-flex items-center gap-2 text-sm text-gold-300"><RefreshCw className="h-4 w-4"/>Refresh</button></div>{busy?<p className="p-6 text-charcoal-300">Loading requests…</p>:orders.length===0?<p className="p-6 text-charcoal-300">No Xerox requests received yet.</p>:<div className="divide-y divide-charcoal-800">{orders.map(o=><OrderRow key={o.id} order={o} inputClass={input} onSave={save} onDownload={download}/>)}</div>}</section></div>
}
function OrderRow({order:o,inputClass,onSave,onDownload}:{order:Order;inputClass:string;onSave:(b:unknown)=>Promise<boolean>;onDownload:(id:string)=>void}){
 const [status,setStatus]=useState(o.status);const [finalPrice,setPrice]=useState(o.final_price==null?'':String(o.final_price));const [notes,setNotes]=useState(o.admin_notes||'');
 return <article className="grid gap-4 p-5 xl:grid-cols-[1fr_auto]"><div><div className="flex flex-wrap items-center gap-3"><b className="text-gold-300">{o.order_number}</b><span className="text-xs text-charcoal-400">{new Date(o.created_at).toLocaleString()}</span></div><p className="mt-2 font-semibold text-white">{o.customer_name} · {o.phone} · {o.email}</p><p className="mt-1 text-sm text-charcoal-300">{o.file_name} · {o.pages} pages × {o.copies} · {o.paper_size} {o.print_type} · {o.print_side} · {o.binding}</p><p className="mt-1 text-sm text-charcoal-300">Estimate ₹{Number(o.estimated_price).toFixed(2)}</p><div className="mt-4 flex flex-wrap gap-2"><select className={inputClass} value={status} onChange={e=>setStatus(e.target.value)}>{['Pending','Accepted','Printing','Ready','Completed','Cancelled'].map(s=><option key={s}>{s}</option>)}</select><input aria-label="Final price" className={`${inputClass} w-32`} placeholder="Final price ₹" type="number" min="0" step=".01" value={finalPrice} onChange={e=>setPrice(e.target.value)}/><input aria-label="Admin notes" className={`${inputClass} min-w-48 flex-1`} placeholder="Admin notes" value={notes} onChange={e=>setNotes(e.target.value)}/><button onClick={()=>onSave({id:o.id,status,final_price:finalPrice,admin_notes:notes})} className="rounded-lg bg-gold-400 px-4 py-2 text-sm font-bold text-burgundy-950">Save update</button></div></div><button onClick={()=>onDownload(o.id)} className="inline-flex h-fit items-center gap-2 rounded-lg border border-charcoal-700 px-3 py-2 text-sm text-white"><Download className="h-4 w-4"/>Secure download</button></article>
}
